# Generated by Django 6.0.4 on 2026-06-20 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('recurring', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'item'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KeywordRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('website', models.URLField()),
                ('found', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('ranking_url', models.URLField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordRankResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serp_rank', models.IntegerField()),
                ('result_type', models.CharField(blank=True, max_length=50)),
                ('title', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('breadcrumb', models.TextField(blank=True)),
                ('keyword_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='projects.keywordrank')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='keywordrank',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.CreateModel(
            name='ProjectChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_checklists', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_checklists', to='projects.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_checklists', to='projects.checklisttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('project_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.projectchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='projects.servicecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='projects.service')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='projects.servicemodule'),
        ),
        migrations.CreateModel(
            name='TaskField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('url', 'URL'), ('number', 'Number'), ('file', 'File'), ('select', 'Dropdown'), ('date', 'Date')], max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('options', models.JSONField(blank=True, null=True)),
                ('checklist_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='projects.checklisttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='projects.activitylog')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.taskfield')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_services', to='projects.project')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_projects', to='projects.service')),
            ],
            options={
                'unique_together': {('project', 'service')},
            },
        ),
    ]
