# Generated by Django 6.0.6 on 2026-06-27 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectservice',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['employee'], name='projects_ac_employe_fc5d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['project_checklist'], name='projects_ac_project_0fc324_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='projects_ac_created_7af476_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrank',
            index=models.Index(fields=['project'], name='projects_ke_project_a6062c_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrank',
            index=models.Index(fields=['activity'], name='projects_ke_activit_1fce6d_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrank',
            index=models.Index(fields=['checked_at'], name='projects_ke_checked_89694b_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrank',
            index=models.Index(fields=['found'], name='projects_ke_found_b9a6ad_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrank',
            index=models.Index(fields=['keyword'], name='projects_ke_keyword_3bb034_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrank',
            index=models.Index(fields=['rank'], name='projects_ke_rank_9289e1_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrank',
            index=models.Index(fields=['project', 'checked_at'], name='projects_ke_project_69499b_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrank',
            index=models.Index(fields=['project', 'keyword'], name='projects_ke_project_205670_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrank',
            index=models.Index(fields=['found', 'checked_at'], name='projects_ke_found_aaf6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrankresult',
            index=models.Index(fields=['keyword_rank'], name='projects_ke_keyword_767f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrankresult',
            index=models.Index(fields=['serp_rank'], name='projects_ke_serp_ra_364291_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrankresult',
            index=models.Index(fields=['result_type'], name='projects_ke_result__7c3642_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrankresult',
            index=models.Index(fields=['domain'], name='projects_ke_domain_c02efb_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityfieldvalue',
            constraint=models.UniqueConstraint(fields=('activity', 'field'), name='unique_activity_field'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('module', 'item'), name='unique_checklist_per_module'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='unique_project_per_client'),
        ),
        migrations.AddConstraint(
            model_name='projectservice',
            constraint=models.UniqueConstraint(fields=('project', 'service'), name='unique_project_service'),
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_service_category_name'),
        ),
        migrations.AddConstraint(
            model_name='servicemodule',
            constraint=models.UniqueConstraint(fields=('service', 'name'), name='unique_module_per_service'),
        ),
        migrations.AddConstraint(
            model_name='taskfield',
            constraint=models.UniqueConstraint(fields=('checklist_template', 'field_name'), name='unique_field_per_template'),
        ),
    ]
