# Generated by Django 6.0.4 on 2026-04-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
