# Generated by Django 6.0.4 on 2026-06-20 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_last_rank_activity_rank_checked_and_more'),
        ('projects', '0002_keywordranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('website', models.URLField()),
                ('found', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('ranking_url', models.URLField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordRankResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serp_rank', models.IntegerField()),
                ('result_type', models.CharField(blank=True, max_length=50)),
                ('title', models.TextField(blank=True)),
                ('domain', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('breadcrumb', models.TextField(blank=True)),
                ('keyword_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='projects.keywordrank')),
            ],
        ),
        migrations.DeleteModel(
            name='KeywordRanking',
        ),
    ]
