# Generated by Django 6.0.4 on 2026-04-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company_name',
        ),
    ]
