# Generated by Django 6.0.4 on 2026-04-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="planned_work",
        ),
    ]
