# Generated by Django 6.0.4 on 2026-06-20 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_checklists', to='projects.project'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='projects.service'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['date'], name='activities__date_dc7081_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['project'], name='activities__project_ce6ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['service_name'], name='activities__service_4bdc22_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['task_type'], name='activities__task_ty_b9be4c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status'], name='activities__status_b1bb4f_idx'),
        ),
    ]
