# Generated by Django 6.0.4 on 2026-06-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_checklist_id_ref_activity_module_id_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='last_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='rank_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='rank_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
