# Generated by Django 6.0.4 on 2026-04-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_approved_at_activity_approved_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='proof_link',
            new_name='proof_links',
        ),
    ]
