# Generated by Django 6.0.4 on 2026-04-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_rename_proof_link_activity_proof_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='proof_links',
            new_name='proof_link',
        ),
    ]
