# Generated by Django 6.0.4 on 2026-06-20 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('business_category', models.CharField(blank=True, max_length=255)),
                ('target_audience', models.TextField(blank=True)),
                ('service_areas', models.TextField(blank=True)),
                ('competitors', models.TextField(blank=True)),
                ('business_description', models.TextField(blank=True)),
                ('hosting_access', models.BooleanField(default=False)),
                ('hosting_provider', models.CharField(blank=True, max_length=255)),
                ('hosting_notes', models.TextField(blank=True)),
                ('domain_access', models.BooleanField(default=False)),
                ('domain_provider', models.CharField(blank=True, max_length=255)),
                ('domain_notes', models.TextField(blank=True)),
                ('ga_access', models.BooleanField(default=False)),
                ('ga_property_id', models.CharField(blank=True, max_length=255)),
                ('ga_notes', models.TextField(blank=True)),
                ('gsc_access', models.BooleanField(default=False)),
                ('gsc_property', models.CharField(blank=True, max_length=255)),
                ('gsc_notes', models.TextField(blank=True)),
                ('google_ads_access', models.BooleanField(default=False)),
                ('google_ads_customer_id', models.CharField(blank=True, max_length=255)),
                ('google_ads_notes', models.TextField(blank=True)),
                ('meta_access', models.BooleanField(default=False)),
                ('meta_business_id', models.CharField(blank=True, max_length=255)),
                ('meta_notes', models.TextField(blank=True)),
                ('youtube_access', models.BooleanField(default=False)),
                ('youtube_channel_name', models.CharField(blank=True, max_length=255)),
                ('youtube_access_email', models.EmailField(blank=True, max_length=254)),
                ('youtube_notes', models.TextField(blank=True)),
                ('social_media_access', models.BooleanField(default=False)),
                ('facebook_page', models.CharField(blank=True, max_length=255)),
                ('instagram_handle', models.CharField(blank=True, max_length=255)),
                ('linkedin_page', models.CharField(blank=True, max_length=255)),
                ('twitter_handle', models.CharField(blank=True, max_length=255)),
                ('social_notes', models.TextField(blank=True)),
                ('kpi_defined', models.BooleanField(default=False)),
                ('reporting_setup', models.BooleanField(default=False)),
                ('team_assigned', models.BooleanField(default=False)),
                ('deliverables_defined', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='clients.client')),
            ],
        ),
    ]
