# Generated by Django 6.0.4 on 2026-05-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequestlog",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("employee", "Employee"),
                    ("qa", "QA"),
                    ("client", "Client"),
                ],
                db_index=True,
                default="employee",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresetrequestlog",
            index=models.Index(fields=["email"], name="accounts_pa_email_44ca89_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresetrequestlog",
            index=models.Index(
                fields=["created_at"], name="accounts_pa_created_95feb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["email"], name="accounts_pa_email_6f6f26_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["created_at"], name="accounts_pa_created_030484_idx"
            ),
        ),
    ]
