# Generated by Django 6.0.4 on 2026-04-23 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
        ('projects', '0003_remove_project_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectserviceassignment',
            unique_together={('project', 'user', 'service')},
        ),
        migrations.AlterField(
            model_name='projectserviceassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
