name: Daily Rank Check

on:
  schedule:
    - cron: '0 5 * * *'

  workflow_dispatch:

jobs:
  rank-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: python manage.py check_daily_ranks
