name: Daily Rank Check

on:
  schedule:
    - cron: '0 5 * * *'   # 10:30 AM IST

  workflow_dispatch:

jobs:
  rank-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Rank Check
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python manage.py check_daily_ranks
