name: Daily Rank Check

on:
  schedule:
    - cron: '0 5 * * *'   # 10:30 AM IST daily
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Rank Check 5 Times
        run: |
          for i in {1..5}
          do
            echo "API Hit $i"
            curl -L https://digital-marketing-q6hei.ondigitalocean.app/api/run-rank-check/
            sleep 5
          done
